Added rollback capability

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,13 +3,16 @@ version: 2
 jobs:
  build:
    machine: true
+
    environment: &environment_variables
-     DOCKER_REPO: chre2628
+     HOME_PROJECT: /home/circleci/project
      DOCKER_CACHE_FROM: latest
      PROJECTS_TO_BUILD: /tmp/projects.to.build
      COMMITTED_FILES: /tmp/committed.files
+     TERRAFORM_VERSION: 0.10.8
      ROLLBACK_ENABLED: false
      ROLLBACK_IMAGE: latest
+
    steps:
       - type: checkout
 
@@ -20,65 +23,82 @@ jobs:
           COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | awk -F'/' '{print $NF}')
           if [[ `echo ${COMMIT_RANGE} | grep "\.\."` != "" ]]; then
             echo "Commit Range: ${COMMIT_RANGE}"
-            git diff $COMMIT_RANGE --name-status | egrep "^[M|A|D]\s+" > ${COMMITTED_FILES}
+            git diff $COMMIT_RANGE --name-status | egrep "^[M|A|D]\s+" | sort | uniq > ${COMMITTED_FILES}
           else
             echo "Commit ID: ${COMMIT_RANGE}"
-            git show $COMMIT_RANGE --name-status | egrep "^[M|A|D]\s+" > ${COMMITTED_FILES}
+            git show $COMMIT_RANGE --name-status | egrep "^[M|A|D]\s+" | sort | uniq > ${COMMITTED_FILES}
+            git --version
           fi
           echo "Grabbing Project Folder Names."
           cat ${COMMITTED_FILES} | awk '{print $2}' | awk -F"/" '{print $1"/"$2}' | sort | uniq | while read line;
           do
-             if [ ! -f "${line}" ]; then
-               echo ${line} >> ${PROJECTS_TO_BUILD}
-             fi
+            if [ ! -f ${line} ]; then
+              echo ${line} >> ${PROJECTS_TO_BUILD} 
+            fi
           done
 
       - type: shell
         name: "Build Projects"
         command: |
           if [[ $(wc -l ${PROJECTS_TO_BUILD} | awk '{print $1}') > 0 ]]; then
+             echo "Processing contents of temporary file..."
              cat ${PROJECTS_TO_BUILD} | while read project;
              do
                dockerImage=$(echo $project | tr '[:upper:]' '[:lower:]' | awk -F'/' '{print $2}')
-               if [ -d "${project}/rollback/rollback.cfg" ]; then     
-                  ROLLBACK_ENABLED=$(grep "ROLLBACK_ENABLED" ${project/rollback/rollback.cfg | awk -F'=' '{print $NF}'})
-                  ROLLBACK_IMAGE=$(grep "ROLLBACK_IMAGE" ${project/rollback/rollback.cfg | awk -F'=' '{print $NF}'})
-                  echo ${ROLLBACK_ENABLED}
-                  echo ${ROLLBACK_IMAGE}
-               fi
+               echo "- Changing to Project Directory: ${dockerImage}"
+               cd ${HOME_PROJECT}/${project} 
                
-               if [ "${ROLLBACK_ENABLED}" == "false" || "${ROLLBACK_ENABLED}" == "" ]; then
-                 if [ -e "${project}/Dockerfile" ]; then
-                    echo "Building ${project}..."
-                    docker login --username "${DOCKER_USERNAME?}" --password "${DOCKER_PASSWORD?}"
-                    docker pull "${DOCKER_REPO?}/${dockerImage}:${DOCKER_CACHE_FROM?}" || true
-                    docker build \
-                       --cache-from "${DOCKER_REPO?}/${dockerImage}:${DOCKER_CACHE_FROM?}" \
-                       --file "${project}/Dockerfile" \
-                       --tag "${DOCKER_REPO?}/${dockerImage}:latest" \
-                       --tag "${DOCKER_REPO?}/${dockerImage}:${CIRCLE_SHA1?}" \
-                       .
-               
-                    echo "Pushing Build Artifact to Docker Repo."
-                    [ ! "${CIRCLE_BRANCH?}" = "master" ] \
-                      && echo "Skipping because this is a pull request" \
-                      || docker push "${DOCKER_REPO?}/${dockerImage}:${CIRCLE_SHA1?}"
+               if [ -e "./rollback/rollback.cfg"]; then
+                  ROLLBACK_ENABLED=$(grep "ROLLBACK_ENABLED" ./rollback/rollback.cfg | awk -F'=' '{print $NF}')
+                  ROLLBACK_IMAGE=$(grep "ROLLBACK_IMAGE" ./rollback/rollback.cfg | awk -F'=' '{print $NF}')
+               fi 
 
-                    echo "Updating latest."
-                    [ ! "${CIRCLE_BRANCH?}" = "master" ] \
-                      && echo "Skipping because this is not a merge into master" \
-                      || docker push "${DOCKER_REPO?}/${dockerImage}:latest"
-                    echo "Build execution complete.\n"
+               if [ "${ROLLBACK_ENABLED}" == "false" || "${ROLLBACK_ENABLED}" == "" ]; then
+                 if [ -e "./Dockerfile" ]; then
+                   echo "  - Build Initiated."
+                   dockerLogin=$(docker login --username "${DOCKER_USERNAME?}" --password "${DOCKER_PASSWORD?}" 2>&1 | grep -v "WARNING")
+                   if [ "${dockerLogin}" != "Login Succeeded" ]; then
+                     echo "    - Docker Login Failed: ERROR - [${dockerLogin}]"
+                     exit 1
+                   else 
+                     echo "    - Docker ${dockerLogin}"
+                   fi
+
+                   echo "    - Performing Docker Build"
+                   docker pull "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${DOCKER_CACHE_FROM?}" 2>/dev/null || true
+                   docker build \
+                     --cache-from "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${DOCKER_CACHE_FROM?}" \
+                     --file "./Dockerfile" \
+                     --tag "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:latest" \
+                     --tag "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}" \
+                     . 1>/tmp/${dockerImage}.log 2>/tmp/${dockerImage}.error
+                    
+                   if [[ $(wc -l /tmp/${dockerImage}.error | awk '{print $1}') > 0 ]]; then
+                     echo "      - Docker Build for ${dockerImage} failed."
+                     exit 1
+                   else 
+                     echo "      - Docker Image Created: hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}"
+                     echo "    - Pushing Build Artifact to Docker Repo."
+                     [ ! "${CIRCLE_BRANCH?}" = "master" ] \
+                       && echo "     - Skipping because this is a pull request" \
+                       || docker push "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}"
+                  
+                     echo "    - Updating latest."
+                     [ ! "${CIRCLE_BRANCH?}" = "master" ] \
+                       && echo "     - Skipping because this is not a merge into master" \
+                       || docker push "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:latest"
+                   fi 
+                   
+                   echo "  - Build execution complete."; echo 
                  else
-                    echo "Skipping build for ${project}. No dockerfile found."
+                   echo "SKIPPING: No dockerfile found for ${project}."
                  fi
                else
-                 echo "Rolling Back Previous To Previous Version of ${dockerImage}"
-                 docker login --username "${DOCKER_USERNAME?}" --password "${DOCKER_PASSWORD?}"
-                 echo " - Rolling Back Using: ${DOCKER_REPO?}/${dockerImage}:${ROLLBACK_IMAGE?}" \
-                    && docker pull "${DOCKER_REPO?}/${dockerImage}:${ROLLBACK_IMAGE?}" 2>/dev/null 
-                    || echo "    - Rollback Failed."
-               fi 
+                 echo " - Rolling Back To Previous Version of ${dockerImage}"
+                 echo "   - Rolling Back Using ${ROLLBACK_IMAGE}" \
+                   && docker pull "chre2628/${dockerImage}:${ROLLBACK_IMAGE}" 2>/dev/null 
+                   || echo "   - Failed to pull ${ROLLBACK_IMAGE}"
+               fi
              done
           else
              echo "There are no projects to build."
