blah...

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -42,49 +42,48 @@ jobs:
              echo "Processing contents of temporary file..."
              cat ${PROJECTS_TO_BUILD} | while read project;
              do
-               if [ -f "${project}" ]; then
-                 echo "- SKIPPING: ${project} is not a project folder."; echo
-               else
-                 dockerImage=$(echo $project | tr '[:upper:]' '[:lower:]' | awk -F'/' '{print $2}')
-                 echo "- Changing to Project Directory: ${dockerImage}"
-                 cd ${HOME_PROJECT}/${project} 
+               dockerImage=$(echo $project | tr '[:upper:]' '[:lower:]' | awk -F'/' '{print $2}')
+               echo "- Changing to Project Directory: ${dockerImage}"
+               cd ${HOME_PROJECT}/${project} 
                  
-                 if [ -e "./Dockerfile" ]; then
-                   echo "  - Build Initiated."
-                   dockerLogin=$(docker login --username "${DOCKER_USERNAME?}" --password "${DOCKER_PASSWORD?}" 2>&1)
-                   if [ ${dockerLogin} != "Login Succeeded" ]; then
-                     echo "    - Docker Login Failed"
-                   fi
-
-                   dockerPull=$(docker pull "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${DOCKER_CACHE_FROM?}" 2>&1) 
-                   echo "    - Docker Pull Status: ${dockerPull}"
-
-                   docker build \
-                     --cache-from "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${DOCKER_CACHE_FROM?}" \
-                     --file "./Dockerfile" \
-                     --tag "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:latest" \
-                     --tag "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}" \
-                     . 1>/tmp/${dockerImage}.log 2>/tmp/${dockerImage}.error
-                     
-                   if [[ $(wc -l /tmp/${dockerImage}.error | awk '{print $1}') > 0 ]]; then
-                     echo "    - Docker Build for ${dockerImage} failed."
-                     exit 1
-                   else 
-                     echo "    - Pushing Build Artifact to Docker Repo."
-                     [ ! "${CIRCLE_BRANCH?}" = "master" ] \
-                       && echo "     - Skipping because this is a pull request" \
-                       || docker push "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}"
-                   
-                     echo "    - Updating latest."
-                     [ ! "${CIRCLE_BRANCH?}" = "master" ] \
-                       && echo "     - Skipping because this is not a merge into master" \
-                       || docker push "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:latest"
-                   fi 
-                   
-                   echo "  - Build execution complete."; echo 
-                 else
-                   echo "SKIPPING: No dockerfile found for ${project}."
+               if [ -e "./Dockerfile" ]; then
+                 echo "  - Build Initiated."
+                 dockerLogin=$(docker login --username "${DOCKER_USERNAME?}" --password "${DOCKER_PASSWORD?}" 2>&1)
+                 if [ "${dockerLogin}" != "Login Succeeded" ]; then
+                   echo "    - Docker Login Failed: ERROR - [${dockerLogin}]"
+                   exit 1
+                 else 
+                   echo "    - Docker ${dockerLogin}"
                  fi
+
+                 dockerPull=$(docker pull "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${DOCKER_CACHE_FROM?}" 2>&1) 
+                 echo "    - Docker Pull Status: ${dockerPull}"
+
+                 docker build \
+                   --cache-from "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${DOCKER_CACHE_FROM?}" \
+                   --file "./Dockerfile" \
+                   --tag "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:latest" \
+                   --tag "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}" \
+                   . 1>/tmp/${dockerImage}.log 2>/tmp/${dockerImage}.error
+                    
+                 if [[ $(wc -l /tmp/${dockerImage}.error | awk '{print $1}') > 0 ]]; then
+                   echo "    - Docker Build for ${dockerImage} failed."
+                   exit 1
+                 else 
+                   echo "    - Pushing Build Artifact to Docker Repo."
+                   [ ! "${CIRCLE_BRANCH?}" = "master" ] \
+                     && echo "     - Skipping because this is a pull request" \
+                     || docker push "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}"
+                  
+                   echo "    - Updating latest."
+                   [ ! "${CIRCLE_BRANCH?}" = "master" ] \
+                     && echo "     - Skipping because this is not a merge into master" \
+                     || docker push "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:latest"
+                 fi 
+                   
+                 echo "  - Build execution complete."; echo 
+               else
+                 echo "SKIPPING: No dockerfile found for ${project}."
                fi
              done
           else
