blah...

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -42,8 +42,8 @@ jobs:
                  
                  if [ -e "./Dockerfile" ]; then
                    echo "  - ${dockerImage} Build Initiated."
-                   docker login --username "${DOCKER_USERNAME?}" --password "${DOCKER_PASSWORD?}"
-                   docker pull "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${DOCKER_CACHE_FROM?}" || true
+                   docker login --username "${DOCKER_USERNAME?}" --password "${DOCKER_PASSWORD?}" 1>/dev/null
+                   docker pull "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${DOCKER_CACHE_FROM?}" 1>/dev/null 2>/dev/null || true
                    docker build \
                      --cache-from "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${DOCKER_CACHE_FROM?}" \
                      --file "./Dockerfile" \
@@ -51,10 +51,11 @@ jobs:
                      --tag "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}" \
                      . 1>/tmp/${dockerImage}.log 2>/tmp/${dockerImage}.error
                      
-                   if [ $(wc -l /tmp/${dockerImage}.error  | grep -v "Error response from daemon" | awk '{print $1}') > 0 ]]; then
+                   if [[ $(wc -l /tmp/${dockerImage}.error  | grep -v "Error response from daemon" | awk '{print $1}') > 0 ]]; then
                      echo "    - Docker Build for ${dockerImage} failed."
                      exit 1
                    else 
+                     cat /tmp/${dockerImage}.log
                      echo "    - Pushing Build Artifact to Docker Repo."
                      [ ! "${CIRCLE_BRANCH?}" = "master" ] \
                        && echo "Skipping because this is a pull request" \
