blah...

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,11 +37,11 @@ jobs:
                  echo " - SKIPPING: ${project} is not a project folder."
                else
                  dockerImage=$(echo $project | tr '[:upper:]' '[:lower:]' | awk -F'/' '{print $2}')
-                 echo " - Changing to Project Directory: ${dockerImage}"
+                 echo "\n- Changing to Project Directory: ${dockerImage}"
                  cd ${HOME_PROJECT}/${project} 
                  
                  if [ -e "./Dockerfile" ]; then
-                   echo " - ${dockerImage} build initiated."
+                   echo "\t- ${dockerImage} Build Initiated."
                    docker login --username "${DOCKER_USERNAME?}" --password "${DOCKER_PASSWORD?}"
                    docker pull "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${DOCKER_CACHE_FROM?}" || true
                    docker build \
@@ -49,19 +49,24 @@ jobs:
                      --file "./Dockerfile" \
                      --tag "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:latest" \
                      --tag "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}" \
-                     .
+                     . 1 > /tmp/${dockerImage}.log 2>/tmp/${dockerImage}.error
+                     
+                   if [ $(wc -l /tmp/${dockerImage}.error | awk '{print $1}') > 0 ]]; then
+                     echo "\t\t- Docker Build for ${dockerImage} failed."
+                     exit 1
+                   else 
+                     echo "\t\t- Pushing Build Artifact to Docker Repo."
+                     [ ! "${CIRCLE_BRANCH?}" = "master" ] \
+                       && echo "Skipping because this is a pull request" \
+                       || docker push "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}"
                    
-                   echo " - Pushing Build Artifact to Docker Repo."
-                   [ ! "${CIRCLE_BRANCH?}" = "master" ] \
-                     && echo "Skipping because this is a pull request" \
-                     || docker push "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:${CIRCLE_SHA1?}"
+                     echo "\t\t- Updating latest."
+                     [ ! "${CIRCLE_BRANCH?}" = "master" ] \
+                       && echo "Skipping because this is not a merge into master" \
+                       || docker push "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:latest"
+                   fi 
                    
-                   echo " - Updating latest."
-                   [ ! "${CIRCLE_BRANCH?}" = "master" ] \
-                     && echo "Skipping because this is not a merge into master" \
-                     || docker push "hautelook/${CIRCLE_PROJECT_REPONAME}-${dockerImage}:latest"
-                   
-                   echo "Build execution complete.\n"
+                   echo "\t- Build execution complete.\n"
                  else
                    echo "SKIPPING: No dockerfile found for ${project}."
                  fi
